[context.production.environment]
NEXT_PUBLIC_MONGODB_URL="mongodb+srv://knandraina:Tsyadinomo0@cluster0.13k7yp8.mongodb.net/"
NEXT_PUBLIC_NODE_ENV="production"

[context.deploy-preview.environment]
NEXT_PUBLIC_MONGODB_URL="mongodb+srv://knandraina:Tsyadinomo0@cluster0.owfo1rt.mongodb.net/test"
NEXT_PUBLIC_NODE_ENV="development"

[context.branch-deploy.environment]
NEXT_PUBLIC_MONGODB_URL="mongodb+srv://knandraina:Tsyadinomo0@cluster0.owfo1rt.mongodb.net/test"
NEXT_PUBLIC_NODE_ENV="development"